const { test, expect } = require('@playwright/test')
const { randomUUID } = require('node:crypto')
const { productId, smallId, mediumId, customer, items } = require('../database.cjs')
const item = { product_id: productId, variant_id: smallId, name: 'Test Lawn Suit', slug: 'test-lawn-suit', size: 'S', price: 2700, sale_price: null, quantity: 1, stock: 5, image_url: '' }
const state = async (request) => (await request.get('http://127.0.0.1:3111/__state')).json()
test.beforeEach(async ({ request }) => { await request.post('http://127.0.0.1:3111/__reset') })
async function fillCustomer(page) {
  await page.getByLabel('Full Name *', { exact: true }).fill(customer.full_name)
  await page.getByLabel('Email *', { exact: true }).fill(customer.email)
  await page.getByLabel('Phone Number *', { exact: true }).fill(customer.phone)
  await page.getByLabel('Full Address *', { exact: true }).fill(customer.address)
  await page.getByLabel('City *', { exact: true }).fill(customer.city)
}
async function seedCart(page) {
  await page.addInitScript((item) => {
    if (!sessionStorage.getItem('test-seeded')) {
      localStorage.setItem('aabroze_cart', JSON.stringify([item]))
      sessionStorage.setItem('test-seeded', '1')
    }
  }, item)
}

test('listing size modal → cart merges sizes, persists and supports quantity/removal', async ({ page }) => {
  await page.goto('/shop')
  await page.locator('.group.relative').filter({ has: page.getByRole('heading', { name: 'Test Lawn Suit', exact: true }) }).getByRole('button', { name: 'Add to Cart', exact: true }).click()
  await expect(page.getByRole('option', { name: /^L / })).toBeDisabled()
  await page.getByRole('option', { name: /^S / }).click()
  await page.getByRole('dialog', { name: 'Select Size' }).getByRole('button', { name: 'Add to Cart', exact: true }).click()
  await page.getByRole('button', { name: 'Close cart' }).click()
  await page.goto('/shop/test-lawn-suit')
  await page.getByRole('button', { name: 'S', exact: true }).click()
  await page.getByRole('button', { name: 'Add to Bag' }).click()
  await page.getByRole('button', { name: 'Close cart' }).click()
  await page.getByRole('button', { name: 'M', exact: true }).click()
  await page.getByRole('button', { name: 'Add to Bag' }).click()
  await page.getByRole('button', { name: 'Close cart' }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Cart (3 items)', exact: true })).toBeVisible()
  await page.goto('/cart')
  await page.setViewportSize({ width: 768, height: 1024 })
  await expect(page.locator('main').getByText('Size: S', { exact: true })).toBeVisible()
  await expect(page.locator('main').getByText('Size: M', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/cart-tablet.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1024, height: 768 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Decrease quantity', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Shopping Bag (2)' })).toBeVisible()
  await page.getByRole('button', { name: 'Remove Test Lawn Suit M' }).click()
  await page.getByRole('button', { name: 'Clear Entire Bag' }).click()
  await expect(page.getByRole('heading', { name: 'Your Bag is Empty' })).toBeVisible()
})

test('checkout validation → one saved COD order → SMTP failure keeps confirmation → refresh', async ({ page, request }) => {
  await seedCart(page)
  await page.goto('/checkout')
  await page.getByRole('button', { name: 'Place Order', exact: true }).click()
  await expect(page.getByText('Enter a valid email address', { exact: true })).toBeVisible()
  await fillCustomer(page)
  await page.getByLabel('Email *', { exact: true }).fill('bad-email')
  await page.getByLabel('Phone Number *', { exact: true }).fill('123')
  await page.getByRole('button', { name: 'Place Order', exact: true }).click()
  await expect(page.getByText('Enter a valid email address', { exact: true })).toBeVisible()
  await fillCustomer(page)
  // Two synchronous submit events must result in one network request.
  let count = 0
  page.on('request', (req) => { if (req.url().endsWith('/api/orders')) count++ })
  await page.locator('form').evaluate((form) => { form.requestSubmit(); form.requestSubmit() })
  await expect(page.getByRole('heading', { name: 'Your order has been placed successfully.' })).toBeVisible()
  expect(count).toBe(1)
  await expect.poll(async () => (await state(request)).jobs.filter((job) => job.last_error).length).toBe(2)
  const saved = await state(request)
  expect(saved.orders).toHaveLength(1)
  expect(Number(saved.orders[0].total)).toBe(2900)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Your order has been placed successfully.' })).toBeVisible()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('aabroze_cart')))).toEqual([])
})

test('mobile Buy Now purchases only selected size and preserves existing cart', async ({ page, request }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await seedCart(page)
  await page.goto('/shop/test-lawn-suit')
  await page.getByRole('button', { name: 'M', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Quantity' }).fill('2')
  await page.getByRole('button', { name: 'Buy Now', exact: true }).click()
  await expect(page).toHaveURL(/mode=buy-now/)
  await page.reload()
  await expect(page.locator('main').getByText('Size: M', { exact: true })).toBeVisible()
  await expect(page.locator('main').getByText('Size: S', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/checkout-mobile.png', fullPage: true })
  await fillCustomer(page)
  await page.getByRole('button', { name: 'Place Order', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Your order has been placed successfully.' })).toBeVisible()
  expect(Number((await state(request)).orders[0].total)).toBe(4600)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('aabroze_cart')))).toEqual([item])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('lost response after commit → refresh → retry returns the same order', async ({ page, request }) => {
  await seedCart(page)
  await page.goto('/checkout')
  await fillCustomer(page)
  await page.route('**/api/orders', async (route) => { await route.fetch(); await route.abort() }, { times: 1 })
  await page.getByRole('button', { name: 'Place Order', exact: true }).click()
  await expect(page.locator('main').getByRole('alert')).toContainText('Retry this checkout')
  const before = await state(request)
  expect(before.orders).toHaveLength(1)
  await page.reload()
  await page.getByRole('button', { name: 'Retry / Confirm Order' }).click()
  await expect(page.getByRole('heading', { name: 'Your order has been placed successfully.' })).toBeVisible()
  const after = await state(request)
  expect(after.orders).toHaveLength(1)
  expect(after.orders[0].order_number).toBe(before.orders[0].order_number)
})

test('API rejects unavailable size and invalid customer, ignores supplied price, protects email retries', async ({ request }) => {
  const bad = await request.post('/api/orders', { data: { customer: { ...customer, email: 'bad' }, items } })
  expect(bad.status()).toBe(400)
  const unavailable = await request.post('/api/orders', { data: { customer, items: [{ ...items[0], quantity: 10 }] } })
  expect(unavailable.status()).toBe(400)
  const placed = await request.post('/api/orders', { data: { customer, items: [{ ...items[0], price: 1 }] } })
  expect(placed.status()).toBe(200)
  expect((await placed.json()).data.total).toBe(5600)
  const competing = await Promise.all([1, 2].map(() => request.post('/api/orders', {
    data: { customer: { ...customer, idempotency_key: randomUUID() }, items: [{ ...items[0], quantity: 2 }] },
  })))
  expect(competing.map((response) => response.status()).sort()).toEqual([200, 400])
  expect((await state(request)).orders).toHaveLength(2)
  expect((await request.post('/api/orders/retry-emails')).status()).toBe(401)
})
